name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: |
          cd projeto_c214
          dart pub get

      - name: Analyze project source
        run: |
          cd projeto_c214
          dart analyze

      - name: Run tests
        run: |
          cd projeto_c214
          flutter test
