name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: flutter/setup-flutter@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: |
          cd projeto_c214
          flutter pub get

      - name: Analyze
        run: |
          cd projeto_c214
          flutter analyze

      - name: Test
        run: |
          cd projeto_c214
          flutter test
