name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: |
          cd projeto_c214
          flutter pub get

      - name: Analyze project source
        run: |
          cd projeto_c214
          flutter analyze

      - name: Run tests
        run: |
          cd projeto_c214
          flutter test
