name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          cache: true
          cache-sdk: true

      - name: Install dependencies
        run: |
          cd projeto_c214
          flutter pub get

      - name: Analyze
        run: |
          cd projeto_c214
          flutter analyze

      - name: Build Web
        run: |
          cd projeto_c214
          flutter build web --release

      - name: Upload Web build artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: projeto_c214/build/web

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          cache: true
          cache-sdk: true

      - name: Install dependencies
        run: |
          cd projeto_c214
          flutter pub get

      - name: Run tests (machine-readable)
        run: |
          cd projeto_c214
          flutter test --machine > test-report.json || true

      - name: Upload test-report artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-test-report
          path: projeto_c214/test-report.json
