name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true

      - name: Install dependencies
        run: |
          cd projeto_c214
          flutter pub get

      - name: Analyze
        run: |
          cd projeto_c214
          flutter analyze

      - name: Test
        run: |
          cd projeto_c214
          flutter test
